import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/index.module.scss';

import fetch from 'node-fetch';

import { ServerDataContext } from '@/utilities/contexts/serverData';

import { iServerData } from '@/utilities/interfaces/serverData';

import Navigation from '@/components/navigation';
import Featured from '@/components/index/featured';
import About from '@/components/index/about';
import Additional from '@/components/index/additional';
import ProductsHeadline from '@/components/index/products-headline';
import Filters from '@/components/index/filters';
import Products from '@/components/index/products';

export async function getServerSideProps() {

  const response = await fetch(`${process.env.API}/api/home`);
  const data = await response.json();

  return {
      props: { data },
  }
}

const Home: NextPage<iServerData> = ({ data }) => {
  return (
    <ServerDataContext.Provider value={data}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Navigation />
          <Featured />
          
          <section className={styles.info}>
            <About />
            <Additional />
          </section>

          <ProductsHeadline />

          <section className={styles.products}>
            <Filters />
            <Products />
          </section>
          
        </main>

      </div>
    </ServerDataContext.Provider>
  )
}

export default Home
