import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/index.module.scss';

import fetch from 'node-fetch';

import Navigation from '@/components/navigation';
import Featured from '@/components/index/featured';
import About from '@/components/index/about';
import Additional from '@/components/index/additional';
import ProductsHeadline from '@/components/index/products-headline';
import Filters from '@/components/index/filters';
import Products from '@/components/index/products';

interface Props {
  data: {
    name: string
  },
}
export async function getServerSideProps() {

  const response = await fetch(`${process.env.API}/api/home`);
  const data = await response.json();

  return {
      props: { data },
  }
}

const Home: NextPage<Props> = ({ data }) => {

  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navigation />
        <Featured />
        
        <section className={styles.info}>
          <About />
          <Additional />
        </section>

        <ProductsHeadline />

        <section className={styles.products}>
          <Filters />
          <Products />
        </section>
         
      </main>

    </div>
  )
}

export default Home
